interface button {
  id: number;
  text: string;
}

export const categories: button[] = [
  { id: 0, text: "Popular" },
  { id: 1, text: "Arts & Culture" },
  { id: 2, text: "Outdoors" },
  { id: 3, text: "Mountains" },
  { id: 4, text: "Beach" },
  { id: 5, text: "Unique stays" },
  { id: 7, text: "Things to do" },
];

export const popular: { subheading: string; subheadingType: string }[] = [
  { subheading: "Canmore", subheadingType: "Holiday rentals" },
  { subheading: "Benalmádena", subheadingType: "Flat rentals" },
  { subheading: "Marbella", subheadingType: "Holiday rentals" },
  { subheading: "Mijas", subheadingType: "Holiday rentals" },
  { subheading: "Prescott", subheadingType: "Holiday rentals" },
  { subheading: "Scottsdale", subheadingType: "Rentals with pools" },
  { subheading: "Tucson", subheadingType: "Flat rentals" },
  { subheading: "Jasper", subheadingType: "Cabin rentals" },
  { subheading: "Mountain View", subheadingType: "House rentals" },
  { subheading: "Devonport", subheadingType: "Holiday rentals" },
  { subheading: "Mallacoota", subheadingType: "Holiday rentals" },
  { subheading: "Ibiza", subheadingType: "Holiday rentals" },
  { subheading: "Anaheim", subheadingType: "Apartment rentals" },
  { subheading: "Monterey", subheadingType: "House rentals" },
  { subheading: "Paso Robles", subheadingType: "Holiday rentals" },
  { subheading: "Santa Barbara", subheadingType: "Pet-friendly rentals" },
  { subheading: "Sonoma", subheadingType: "House rentals" },
  { subheading: "Show More ⮟", subheadingType: " " },
];

export const art: { subheading: string; subheadingType: string }[] = [
  { subheading: "Phoenix", subheadingType: "Apartment rentals" },
  { subheading: "Hot Springs", subheadingType: "House rentals" },
  { subheading: "Los Angeles", subheadingType: "Bed and breakfasts" },
  { subheading: "San Diego", subheadingType: "Flat rentals" },
  { subheading: "San Francisco", subheadingType: "Holiday rentals" },
  { subheading: "Barcelona", subheadingType: "Holiday rentals" },
  { subheading: "Prague", subheadingType: "Holiday rentals" },
  { subheading: "Washington", subheadingType: "Pet-friendly rentals" },
  { subheading: "Keswick", subheadingType: "Cottage rentals" },
  { subheading: "London", subheadingType: "Villa rentals" },
  { subheading: "Scarborough", subheadingType: "Holiday rentals" },
  { subheading: "Sherwood Forest", subheadingType: "Cabin rentals" },
  { subheading: "York", subheadingType: "Pet-friendly rentals" },
  { subheading: "Paris", subheadingType: "Villa rentals" },
  { subheading: "Rhodes", subheadingType: "Flat rentals" },
  { subheading: "Nashville", subheadingType: "Holiday rentals" },
  { subheading: "Dublin", subheadingType: "House rentals" },
];

export const outdoors: { subheading: string; subheadingType: string }[] = [
  { subheading: "Lake Martin", subheadingType: "Flat rentals" },
  { subheading: "Banff", subheadingType: "Holiday rentals" },
  { subheading: "Nerja", subheadingType: "House rentals" },
  { subheading: "Greer", subheadingType: "Cabin rentals" },
  { subheading: "Lake Havasu City", subheadingType: "House rentals" },
  { subheading: "Lake Powell", subheadingType: "Holiday rentals" },
  { subheading: "North Rim", subheadingType: "Holiday rentals" },
  { subheading: "Payson", subheadingType: "Holiday rentals" },
  { subheading: "Pinetop-Lakeside", subheadingType: "Cabin rentals" },
  { subheading: "Red Rock", subheadingType: "Cabin rentals" },
  { subheading: "Dinner Plain", subheadingType: "Holiday rentals" },
  { subheading: "Streaky Bay", subheadingType: "Holiday rentals" },
  { subheading: "Emerald Lake", subheadingType: "Holiday rentals" },
  { subheading: "Vancouver Island", subheadingType: "Pet-friendly rentals" },
  { subheading: "Victoria", subheadingType: "Beach house rentals" },
  { subheading: "Idyllwild-Pine Cove", subheadingType: "Holiday rentals" },
  { subheading: "Mammoth Lakes", subheadingType: "Holiday rentals" },
];

export const mountains: { subheading: string; subheadingType: string }[] = [
  { subheading: "Mentone", subheadingType: "House rentals" },
  { subheading: "Sedona", subheadingType: "Villa rentals" },
  { subheading: "Helen", subheadingType: "Cabin rentals" },
  { subheading: "Pine Mountain", subheadingType: "Holiday rentals" },
  { subheading: "Stone Mountain", subheadingType: "Holiday rentals" },
  { subheading: "Island Park", subheadingType: "Holiday rentals" },
  { subheading: "Blue Mountains", subheadingType: "Chalet rentals" },
  { subheading: "Asheville", subheadingType: "Holiday rentals" },
  { subheading: "Blowing Rock", subheadingType: "Cabin rentals" },
  { subheading: "Boone", subheadingType: "Holiday rentals" },
  { subheading: "Hochatown", subheadingType: "Holiday rentals" },
  { subheading: "Pigeon Forge", subheadingType: "Holiday rentals" },
  { subheading: "Townsend", subheadingType: "Holiday rentals" },
  { subheading: "Wears Valley", subheadingType: "Holiday rentals" },
  { subheading: "Cabins", subheadingType: "Holiday rentals" },
];

export const beach: { subheading: string; subheadingType: string }[] = [
  { subheading: "Dauphin Island", subheadingType: "Flat rentals" },
  { subheading: "Fort Morgan", subheadingType: "Holiday rentals" },
  { subheading: "Gulf Shores", subheadingType: "Holiday rentals" },
  { subheading: "Bruny Island", subheadingType: "Holiday rentals" },
  { subheading: "Crescent Head", subheadingType: "Holiday rentals" },
  { subheading: "Gerringong", subheadingType: "Holiday rentals" },
  { subheading: "Hamilton Island", subheadingType: "House rentals" },
  { subheading: "Lancelin", subheadingType: "Holiday rentals" },
  { subheading: "Melbourne Beach", subheadingType: "Cottage rentals" },
  { subheading: "Moonta Bay", subheadingType: "Beachfront rentals" },
  { subheading: "Ocean Grove", subheadingType: "Holiday rentals" },
  { subheading: "Majorca", subheadingType: "Chalet rentals" },
  { subheading: "Big Sur", subheadingType: "Beach house rentals" },
  { subheading: "Bodega Bay", subheadingType: "Holiday rentals" },
  { subheading: "Cambria", subheadingType: "Holiday rentals" },
  { subheading: "Cayucos", subheadingType: "Holiday rentals" },
  { subheading: "Huntington Beach", subheadingType: "Holiday rentals" },
];

export const stays: { subheading: string; subheadingType: string }[] = [
  { subheading: "Yurt Rentals", subheadingType: "United States" },
  { subheading: "Yurt Rentals", subheadingType: "United Kingdom" },
  { subheading: "Castle Rentals", subheadingType: "United States" },
  { subheading: "Houseboats", subheadingType: "United States" },
  { subheading: "Holiday Caravans", subheadingType: "United Kingdom" },
  { subheading: "Private Island Rentals", subheadingType: "United States" },
  { subheading: "Farm Houses", subheadingType: "United States" },
  { subheading: "Farm Cottages", subheadingType: "United Kingdom" },
  { subheading: "Cabin Rentals", subheadingType: "Australia" },
  { subheading: "Luxury Cabins", subheadingType: "United Kingdom" },
  { subheading: "Luxury Cabins", subheadingType: "United States" },
  { subheading: "Holiday Chalets", subheadingType: "United Kingdom" },
  { subheading: "Cottage Rentals", subheadingType: "United States" },
  { subheading: "Holiday Cottages", subheadingType: "United Kingdom" },
  { subheading: "Mansion Rentals", subheadingType: "United States" },
  { subheading: "Villa Rentals", subheadingType: "United Kingdom" },
  { subheading: "Holiday Bungalows", subheadingType: "United Kingdom" },
];

export const things: { subheading: string; subheadingType: string }[] = [
  { subheading: "London", subheadingType: "England" },
  { subheading: "Paris", subheadingType: "Île-de-France" },
  { subheading: "New York", subheadingType: "New York" },
  { subheading: "Barcelona", subheadingType: "Catalonia" },
  { subheading: "İstanbul", subheadingType: "İstanbul" },
  { subheading: "Bali", subheadingType: "Indonesia" },
  { subheading: "Amsterdam", subheadingType: "North Holland" },
  { subheading: "Miami", subheadingType: "Florida" },
  { subheading: "Madrid", subheadingType: "Community of Madrid" },
  { subheading: "Los Angeles", subheadingType: "California" },
  { subheading: "Rome", subheadingType: "Lazio" },
  { subheading: "Lisbon", subheadingType: "Lisbon" },
  { subheading: "Tokyo", subheadingType: "Tokyo" },
  { subheading: "Vienna", subheadingType: "Vienna" },
  { subheading: "Athens", subheadingType: "Greece" },
  { subheading: "Prague", subheadingType: "Czechia" },
  { subheading: "Orlando", subheadingType: "Florida" },
];
