import img1 from "../assets/img1.jpg";
import img2 from "../assets/img2.jpg";
import img3 from "../assets/img3.jpg";
import img4 from "../assets/img4.jpg";
import img5 from "../assets/img5.jpg";
import img6 from "../assets/img6.jpg";
import img7 from "../assets/img7.jpg";
import img8 from "../assets/img8.jpg";
import img9 from "../assets/img9.jpg";

export const listings = [
  {
    id: 1,
    location: "Smithville, Tennessee, US",
    imageUrl: img2,
    price: "12,000",
    distance: "34 kilometers away",
    rating: 4.88,
    priceUnit: "night",
    booking_date_range: "10-12 Apr",
  },
  {
    id: 2,
    location: "Asheville, North Carolina, US",
    imageUrl: img4,
    price: "15,000",
    distance: "45 kilometers away",
    rating: 4.92,
    priceUnit: "night",
    booking_date_range: "15-17 May",
  },
  {
    id: 3,
    location: "Savannah, Georgia, US",
    imageUrl: img8,
    price: "18,000",
    distance: "22 kilometers away",
    rating: 4.75,
    priceUnit: "night",
    booking_date_range: "22-24 Jun",
  },
  {
    id: 4,
    location: "Charleston, South Carolina, US",
    imageUrl: img6,
    price: "20,000",
    distance: "18 kilometers away",
    rating: 4.85,
    priceUnit: "night",
    booking_date_range: "5-7 Aug",
  },
  {
    id: 5,
    location: "Gatlinburg, Tennessee, US",
    imageUrl: img8,
    price: "16,000",
    distance: "27 kilometers away",
    rating: 4.9,
    priceUnit: "night",
    booking_date_range: "12-14 Sep",
  },
  {
    id: 6,
    location: "Asheville, North Carolina, US",
    imageUrl: img9,
    price: "18,000",
    distance: "39 kilometers away",
    rating: 4.88,
    priceUnit: "night",
    booking_date_range: "19-21 Oct",
  },
  {
    id: 7,
    location: "Savannah, Georgia, US",
    imageUrl: img2,
    price: "22,000",
    distance: "25 kilometers away",
    rating: 4.81,
    priceUnit: "night",
    booking_date_range: "26-28 Nov",
  },
  {
    id: 8,
    location: "Charleston, South Carolina, US",
    imageUrl: img5,
    price: "24,000",
    distance: "14 kilometers away",
    rating: 4.93,
    priceUnit: "night",
    booking_date_range: "3-5 Dec",
  },
  {
    id: 9,
    location: "Gatlinburg, Tennessee, US",
    imageUrl: img2,
    price: "20,000",
    distance: "31 kilometers away",
    rating: 4.87,
    priceUnit: "night",
    booking_date_range: "10-12 Jan",
  },
  {
    id: 10,
    location: "Pigeon Forge, Tennessee, US",
    imageUrl: img5,
    price: "18,000",
    distance: "24 kilometers away",
    rating: 4.84,
    priceUnit: "night",
    booking_date_range: "17-19 Feb",
  },
  {
    id: 22,
    location: "Agra, India",
    imageUrl: img4,
    price: "3,999",
    distance: "180 kilometers away",
    rating: 4.93,
    priceUnit: "night",
    booking_date_range: "3-18 June",
  },
  {
    id: 23,
    location: "Haryana, India",
    imageUrl: img6,
    price: "34,235",
    distance: "42 kilometers away",
    booking_date_range: "9-14 Apr",
    rating: 5.0,
    priceUnit: "night",
  },
  {
    id: 24,
    location: "Rishikesh, India",
    imageUrl: img5,
    price: "28,500",
    distance: "201 kilometers away",
    rating: 4.78,
    booking_date_range: "1-6 Aug",
    priceUnit: "night",
  },
  {
    id: 25,
    location: "Moradabad, India",
    imageUrl: img6,
    price: "8,559",
    distance: "151 kilometers away",
    rating: 4.8,
    booking_date_range: "7-12 Apr",
    priceUnit: "night",
  },
  {
    id: 26,
    location: "Smithville, Tennessee, US",
    imageUrl: img7,
    price: "12,000",
    distance: "34 kilometers away",
    rating: 4.88,
    priceUnit: "night",
    booking_date_range: "10-12 Apr",
  },
  {
    id: 27,
    location: "Gatlinburg, Tennessee, US",
    imageUrl: img8,
    price: "15,500",
    distance: "30 kilometers away",
    rating: 4.72,
    priceUnit: "night",
    booking_date_range: "21-24 Mar",
  },
  {
    id: 28,
    location: "Jaipur, India",
    imageUrl: img6,
    price: "7,200",
    distance: "260 kilometers away",
    booking_date_range: "10-15 Jul",
    rating: 4.76,
    priceUnit: "night",
  },
  {
    id: 29,
    location: "Manali, India",
    imageUrl: img5,
    price: "9,999",
    distance: "315 kilometers away",
    booking_date_range: "5-10 Sep",
    rating: 4.89,
    priceUnit: "night",
  },
  {
    id: 30,
    location: "Shimla, India",
    imageUrl: img3,
    price: "12,750",
    distance: "380 kilometers away",
    booking_date_range: "12-18 Oct",
    rating: 4.67,
    priceUnit: "night",
  },
  {
    id: 11,
    location: "Mussoorie, India",
    imageUrl: img7,
    price: "11,450",
    distance: "250 kilometers away",
    rating: 4.98,
    priceUnit: "night",
    booking_date_range: "20-25 Jun",
  },
  {
    id: 12,
    location: "Ooty, India",
    imageUrl: img4,
    price: "6,800",
    distance: "420 kilometers away",
    booking_date_range: "2-7 Nov",
    rating: 4.81,
    priceUnit: "night",
  },
  {
    id: 13,
    location: "Kodaikanal, India",
    imageUrl: img8,
    price: "10,250",
    distance: "380 kilometers away",
    booking_date_range: "14-20 Dec",
    rating: 4.95,
    priceUnit: "night",
  },
  {
    id: 14,
    location: "Nainital, India",
    imageUrl: img3,
    price: "8,999",
    distance: "290 kilometers away",
    booking_date_range: "18-23 Mar",
    rating: 4.82,
    priceUnit: "night",
  },
  {
    id: 15,
    location: "Coorg, India",
    imageUrl: img5,
    price: "9,750",
    distance: "350 kilometers away",
    booking_date_range: "7-13 Apr",
    rating: 4.79,
    priceUnit: "night",
  },
  {
    id: 16,
    location: "Munnar, India",
    imageUrl: img1,
    price: "7,999",
    distance: "410 kilometers away",
    booking_date_range: "25-30 Aug",
    rating: 4.88,
    priceUnit: "night",
  },
  {
    id: 17,
    location: "Alleppey, India",
    imageUrl: img2,
    price: "11,999",
    distance: "440 kilometers away",
    rating: 4.97,
    priceUnit: "night",
    booking_date_range: "8-12 Sep",
  },
  {
    id: 18,
    location: "Kerala, India",
    imageUrl: img4,
    price: "13,500",
    distance: "450 kilometers away",
    booking_date_range: "20-26 Oct",
    rating: 4.84,
    priceUnit: "night",
  },
  {
    id: 19,
    location: "Goa, India",
    imageUrl: img5,
    price: "14,750",
    distance: "550 kilometers away",
    booking_date_range: "5-11 Nov",
    rating: 4.92,
    priceUnit: "night",
  },
  {
    id: 20,
    location: "Mumbai, India",
    imageUrl: img6,
    price: "19,999",
    distance: "680 kilometers away",
    booking_date_range: "12-17 Dec",
    rating: 4.87,
    priceUnit: "night",
  },
  {
    id: 33,
    location: "Pune, India",
    imageUrl: img9,
    price: "34,235",
    distance: "42 kilometers away",
    booking_date_range: "10-18 Apr",
    rating: 4.5,
    priceUnit: "night",
  },
  {
    id: 32,
    location: "Bangalore, India",
    imageUrl: img7,
    price: "34,235",
    distance: "742 kilometers away",
    booking_date_range: "15-21 Apr",
    rating: 4.9,
    priceUnit: "night",
  },
  {
    id: 42,
    location: "Sonipat, India",
    imageUrl: img6,
    price: "34,235",
    distance: "742 kilometers away",
    booking_date_range: "15-21 Apr",
    rating: 4.9,
    priceUnit: "night",
  },
];
